<div class="entry-edit">
    <form action="<?php echo $this->getFormUrl() ?>" id="shippingmethod_form" method="POST">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <div style="float: right;"><button title="Save" type="submit" class="scalable save"><span><span><span>Save</span></span></span></button></div>
            <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass() . ' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
        </div>
        <div class="fieldset">
            <?php //echo $this->getChildHtml('shippingMethodForm') 
            ?>
        </div>
    </form>
</div>