<?php $methods = $this->getPayemntMethodTitle() ?>
<form action="<?php echo $this->getUrl('*/Adminhtml_Order_Cart/paymentMethod'); ?>" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <fieldset class="np">
        <div class="edit-form" id="order-shipping_address_fields">
            <div class="content">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <?php foreach ($methods as $key => $value) : ?>
                            <tbody>
                                <tr>
                                    <td><input type="radio" name="billingMethod" id="<?php echo $key ?>" value="<?php echo $key ?>" <?php if ($value->getId() == $this->fetchPaymentMethod()) {
                                                                                                                                        echo "checked";
                                                                                                                                    } ?>>
                                        <label for="<?php echo $key ?>"><?php echo $key ?></label><br>
                                    </td>
                                </tr>
                            </tbody>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
        <div class="save">
            <button class="button" type="submit" onclick="mage.formSubmit(this)">Save Payment Method</button>
        </div>
    </fieldset>
</form>