<?php /* echo '<pre>';
print_r($this->getCart());
print_r($this->getChild('billing_address')->getBillingAddress());
$address =  $this->getChild('billing_address')->setCart($this->getCart());
echo $address->_toHtml() */ ?>
<form action="<?php echo $this->getUrl('*/Adminhtml_Order_Cart/Save') ?>" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="page-create-order">
        <table cellspacing="0" width="100%">
            <tr>

                <td <?php if ($this->getCustomerId()) : ?>class="main-col" <?php endif; ?>>

                    <div id="order-search" class="order-search-items"><?php echo $this->getChildHtml('search') ?></div>
                    <div id="order-items"><?php echo $this->getChild('items_grid')->setCart($this->getCart())->toHtml(); ?></div>
                    <div id="order-addresses">
                        <div id="order-billing_address" class="box-left"><?php echo $this->getChild('billing_address')->setCart($this->getCart())->toHtml(); ?></div>
                        <div id="order-shipping_address" class="box-right"><?php echo $this->getChild('shipping_address')->setCart($this->getCart())->toHtml(); ?></div>
                    </div>
                    <div class="clear"></div>
                    <div id="order-methods">
                        <div class="entry-edit box-left">
                            <div class="entry-edit-head">
                                <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass() . ' icon-head' : '' ?>">Shipping Method</h4>
                            </div>
                            <div class="fieldset">
                                <?php echo $this->getChildHtml('shipping_method') ?>
                            </div>
                        </div>
                        <div class="entry-edit box-right">
                            <div class="entry-edit-head">
                                <div style="float: right;"><?php echo $this->getButtonsHtml() ?></div>
                                <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass() . ' icon-head' : '' ?>">Payment Method</h4>
                            </div>
                            <div class="fieldset">
                                <?php echo $this->getChildHtml('billing_method') ?>
                            </div>
                        </div>




                        <div class="clear"></div>
                </td>
            </tr>
        </table>
    </div>
</form>